name: dotnet-build

on:
  workflow_dispatch:

jobs:
  first-build:
    environment: ${{ github.ref_name }}
    runs-on: [self-hosted]
    steps:
      - id: repository
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.event.repository.name }}
      - id: branch
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.ref_name }}
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Docker Build Package
        run: |
          #docker build . --file Dockerfile --tag consoleapp
          docker build . --file Dockerfile --tag 10.244.0.22:5000/${{steps.repository.outputs.lowercase}}/${{steps.branch.outputs.lowercase}}:latest
          docker tag 10.244.0.22:5000/${{steps.repository.outputs.lowercase}}/${{steps.branch.outputs.lowercase}}:latest 10.244.0.22:5000/${{steps.repository.outputs.lowercase}}/${{steps.branch.outputs.lowercase}}:${{github.run_number}} 
          docker push 10.244.0.22:5000/${{steps.repository.outputs.lowercase}}/${{steps.branch.outputs.lowercase}}:latest
          #docker push 10.244.0.22:5000/${{steps.repository.outputs.lowercase}}/${{steps.branch.outputs.lowercase}}:${{github.run_number}} 
  